version: '3.9'

services:
  app-backend:
    container_name: app-backend
    image: app-backend
    depends_on:
      - app-postgres
      - elasticsearch
    ports:
      - "8080:8080"
    networks:
      - app-network
    env_file:
      - .env

  app-postgres:
    image: postgres:16-alpine
    container_name: app-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - app-postgres:/var/lib/postgresql/data/
    networks:
      - app-network

  elasticsearch:
    image: elasticsearch:7.17.23
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    networks:
      - app-network

volumes:
  app-postgres:
    driver: local

networks:
  app-network:
    driver: bridge


